# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HelloMark' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'PubNub'
  pod 'ApiAI/Core'
  pod 'ApiAI/VoiceRequest'
  pod 'ApiAI/UIKit'
  pod 'ApiAI/ResponseMapping'
  pod 'MBProgressHUD'

  target 'HelloMarkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HelloMarkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
